baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'homepage of b1ttersuess'
theme = 'not-much'

# Controls the navigation
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"
  weight = 3

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "GitHub"
  url = "https://github.com/b1ttersuess"
  weight = 4
