name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures theme is included
          fetch-depth: 0

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          echo "Running Hugo build..."
          hugo --gc --minify --destination public --baseURL "${{ steps.pages.outputs.base_url }}/" || { echo "Hugo build failed!" >&2; exit 1; }

      - name: Debug Hugo Output
        run: |
          echo "Checking Hugo output..."
          ls -lah ./public || { echo "⚠️ public/ directory not found! Hugo build likely failed."; exit 1; }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: github-pages

      - name: List Uploaded Artifacts
        run: |
          echo "Checking uploaded artifacts..."
          ls -lah ${{ runner.temp }}/pages-artifacts/ || echo "⚠️ No artifacts found!"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3